const PRODUCTS = [
  {
    id: 1,
    name: "PlayStation 5 Disc Edition",
    desc: "Consola PS5 con lector de discos, control DualSense y cables incluidos.",
    price: 580000,
    category: "playstation",
    condition: "nuevo",
    icon: "assets/PlayStationDiscEdition.webp",
    inStock: true,
  },
  {
    id: 2,
    name: "FIFA 25 / EA Sports FC 25",
    desc: "Versión física para PS5. El juego de fútbol más completo del mercado.",
    price: 28000,
    originalPrice: 35000,
    category: "juegos",
    condition: "oferta",
    icon: "assets/fifa25.webp",
    inStock: true,
  },
  {
    id: 3,
    name: "Nintendo Switch OLED",
    desc: "Consola Switch versión OLED, pantalla de 7 pulgadas, colores vibrantes.",
    price: 420000,
    category: "nintendo",
    condition: "nuevo",
    icon: "assets/nintendo.webp",
    inStock: true,
  },
  {
    id: 4,
    name: "Control DualSense Blanco",
    desc: "Control inalámbrico PS5 original. Gatillos adaptativos y háptica avanzada.",
    price: 65000,
    originalPrice: 80000,
    category: "accesorios",
    condition: "oferta",
    icon: "assets/dual sense.webp",
    inStock: true,
  },
  {
    id: 5,
    name: "PC Armada Gamer RTX 4060",
    desc: "PC gamer completa: Ryzen 5 7600, RTX 4060, 16GB RAM DDR5, SSD 1TB.",
    price: 1850000,
    category: "pc",
    condition: "nuevo",
    icon: "assets/pc armada.webp",
    inStock: true,
  },
  {
    id: 6,
    name: "PS4 Pro 1TB",
    desc: "Consola PS4 Pro en excelente estado, 2 controles y 5 juegos incluidos.",
    price: 210000,
    category: "playstation",
    condition: "usado",
    icon: "assets/ps4.webp",
    inStock: true,
  },
  {
    id: 7,
    name: "Headset Gaming HyperX Cloud",
    desc: "Auriculares gamer con sonido envolvente 7.1, micrófono desmontable.",
    price: 55000,
    category: "accesorios",
    condition: "nuevo",
    icon: "assets/eadsetGamingHyperXCloud.webp",
    inStock: true,
  },
  {
    id: 8,
    name: "Caja Random Gaming",
    desc: "¡Sorpresa! Juegos, accesorios o periféricos aleatorios. Siempre vale más de lo que pagás.",
    price: 15000,
    category: "accesorios",
    condition: "nuevo",
    icon: "assets/caja misteriosa.webp",
    inStock: true,
  },
  {
    id: 9,
    name: "The Last of Us Part II",
    desc: "Edición especial para PS4/PS5. Juego narrativo de acción aclamado por la crítica.",
    price: 22000,
    category: "juegos",
    condition: "usado",
    icon: "assets/TheLastofUsPartII.webp",
    inStock: true,
  },
  {
    id: 10,
    name: "Monitor Gamer 144Hz 24\"",
    desc: "Panel IPS Full HD, 1ms de respuesta, compatible con PS5 y PC.",
    price: 185000,
    category: "pc",
    condition: "nuevo",
    icon: "assets/MonitorGamer144Hz.webp",
    inStock: false,
  },
  {
    id: 11,
    name: "Nintendo Switch Joy-Con Neón",
    desc: "Controles Joy-Con originales de Nintendo, par, colores rojo y azul neón.",
    price: 38000,
    category: "nintendo",
    condition: "nuevo",
    icon: "assets/nintendo.webp",
    inStock: true,
  },
  {
    id: 12,
    name: "Teclado Mecánico Gamer RGB",
    desc: "Switches mecánicos azules, retroiluminación RGB, diseño compacto TKL.",
    price: 48000,
    originalPrice: 60000,
    category: "pc",
    condition: "oferta",
    icon: "assets/TecladoMecánicoGamerGB.webp",
    inStock: true,
  },
];

const CATEGORIES = [
  { id: "todos",       label: "Todo",        icon: "🎯" },
  { id: "playstation", label: "PlayStation", icon: "🎮" },
  { id: "nintendo",    label: "Nintendo",    icon: "🕹️" },
  { id: "pc",          label: "PC Gamer",    icon: "🖥️" },
  { id: "juegos",      label: "Juegos",      icon: "💿" },
  { id: "accesorios",  label: "Accesorios",  icon: "🎧" },
];

const CONDITIONS = [
  { id: "todos",  label: "Todos" },
  { id: "nuevo",  label: "Nuevo" },
  { id: "usado",  label: "Usado" },
  { id: "oferta", label: "Oferta" },
];

const REVIEWS = [
  {
    stars: 5,
    text: "Compré la PS5 y llegó en perfectas condiciones. Súper rápido el envío a Morón. Los recomiendo 100%!",
    name: "Matías R.",
    location: "Morón, GBA",
    avatar: "M",
  },
  {
    stars: 5,
    text: "Llevé mi PS4 a reparar y en 2 días estaba lista. Precio justo y muy buena atención. Ya volví dos veces.",
    name: "Carla V.",
    location: "Ituzaingó, GBA",
    avatar: "C",
  },
  {
    stars: 5,
    text: "La caja random fue una sorpresa increíble, me tocaron 3 juegos que valen el doble. Volvería a comprar!",
    name: "Franco L.",
    location: "Haedo, GBA",
    avatar: "F",
  },
  {
    stars: 5,
    text: "Armaron mi PC gamer en tiempo récord. Súper profesionales, buen precio y me explicaron todo. 10 puntos.",
    name: "Valentina G.",
    location: "Palermo, CABA",
    avatar: "V",
  },
];

const PHONE = "5491162855278";
const WSP_BASE = `https://wa.me/${PHONE}`;
